etc/25nssdatabases: Update from schroot 20nssdatabases
Skip comments and blank lines in nssdatabases file
Skip copying if source and destination are identical, preventing
blanking the file if it's hardlinked or bind mounted.
Use strict POSIX shell.

diff --git a/etc/25nssdatabases b/etc/25nssdatabases
--- a/etc/25nssdatabases
+++ b/etc/25nssdatabases
@@ -19,8 +19,6 @@
 
 set -e
 
-NSSDATABASES="/etc/sbuild/nssdatabases-defaults"
-
 if [ -f "$CHROOT_SCRIPT_CONFIG" ]; then
     . "$CHROOT_SCRIPT_CONFIG"
 elif [ "$2" = "ok" ]; then
@@ -48,6 +46,23 @@ if [ $1 = "setup-start" ] || [ $1 = "setup-recover" ]; then
     if [ -n "$NSSDATABASES" ]; then
 	if [ -f "$NSSDATABASES" ]; then
 	    while read db; do
+		if echo "$db" | egrep -q '^(#|$)' ; then
+                    continue
+		fi
+
+                # Device and inode
+		dr=$(/usr/bin/stat --format="%d %i" "/etc/$db")
+                # This one can fail since it might not exist yet
+		dc=$(/usr/bin/stat --format="%d %i" "${CHROOT_PATH}/etc/$db" 2>/dev/null || :)
+
+                # If the database inside and outside the chroot is the
+                # same, it's very likely that dup_nss would blank the
+                # database, so skip it.
+		if [ "$dr" = "$dc" ]; then
+		    echo "warning: $db files '/etc/$db' and '${CHROOT_PATH}/etc/$db' are the same file; skipping" 1>&2
+                    continue;
+		fi
+
 		dup_nss "$db" "${CHROOT_PATH}/etc/$db"
 	    done < "$NSSDATABASES"
 	else
